package com.studenthub.dao;
import com.studenthub.model.Attachment;import com.studenthub.util.AttachmentUpload;import com.studenthub.util.DBConnection;import java.sql.*;import java.util.*;
public class AttachmentDAO {
 public long insert(Connection c,String owner,long id,AttachmentUpload u)throws SQLException{String column=switch(owner){case"POST"->"post_id";case"COMMENT"->"comment_id";case"MESSAGE"->"message_id";default->throw new IllegalArgumentException("owner");};String sql="INSERT INTO attachments("+column+",original_filename,storage_key,mime_type,file_size) VALUES(?,?,?,?,?)";try(PreparedStatement s=c.prepareStatement(sql,Statement.RETURN_GENERATED_KEYS)){s.setLong(1,id);s.setString(2,u.originalFilename());s.setString(3,u.storageKey());s.setString(4,u.mimeType());s.setLong(5,u.fileSize());s.executeUpdate();try(ResultSet r=s.getGeneratedKeys()){return r.next()?r.getLong(1):0;}}}
 public Optional<Attachment> findById(long id)throws SQLException{try(Connection c=DBConnection.getConnection();PreparedStatement s=c.prepareStatement("SELECT * FROM attachments WHERE attachment_id=?")){s.setLong(1,id);try(ResultSet r=s.executeQuery()){return r.next()?Optional.of(map(r)):Optional.empty();}}}
 public boolean visibleTo(Attachment a,long userId)throws SQLException{if(a.postId()!=null)return new PostDAO().findVisibleById(a.postId(),userId).isPresent();if(a.commentId()!=null){try(Connection c=DBConnection.getConnection();PreparedStatement s=c.prepareStatement("SELECT post_id FROM comments WHERE comment_id=?")){s.setLong(1,a.commentId());try(ResultSet r=s.executeQuery()){return r.next()&&new PostDAO().findVisibleById(r.getLong(1),userId).isPresent();}}}if(a.messageId()!=null){String sql="SELECT r.room_type,r.semester,r.section_name,u.role,u.semester viewer_semester,u.section_name viewer_section FROM messages m JOIN chat_rooms r ON r.room_id=m.room_id JOIN users u ON u.user_id=? WHERE m.message_id=?";try(Connection c=DBConnection.getConnection();PreparedStatement s=c.prepareStatement(sql)){s.setLong(1,userId);s.setLong(2,a.messageId());try(ResultSet x=s.executeQuery()){if(!x.next())return false;com.studenthub.model.DiscussionScope scope=com.studenthub.model.DiscussionScope.valueOf(x.getString("room_type"));Integer sem=(Integer)x.getObject("viewer_semester");String sec=x.getString("viewer_section");if(!com.studenthub.util.DiscussionAccess.roleMayAccess(scope,x.getString("role")))return false;if(com.studenthub.util.DiscussionAccess.denialReason(scope,sem,sec)!=null)return false;return com.studenthub.util.DiscussionAccess.matches(scope,sem,sec,(Integer)x.getObject("semester"),x.getString("section_name"));}}}return false;}
 public Map<Long,Attachment> findFor(String owner,Collection<Long> ids)throws SQLException{if(ids.isEmpty())return Map.of();String col=switch(owner){case"POST"->"post_id";case"COMMENT"->"comment_id";case"MESSAGE"->"message_id";default->throw new IllegalArgumentException();};String marks=String.join(",",Collections.nCopies(ids.size(),"?"));Map<Long,Attachment> out=new HashMap<>();try(Connection c=DBConnection.getConnection();PreparedStatement s=c.prepareStatement("SELECT * FROM attachments WHERE "+col+" IN ("+marks+")")){int i=1;for(long id:ids)s.setLong(i++,id);try(ResultSet r=s.executeQuery()){while(r.next())out.put(r.getLong(col),map(r));}}return out;}
 public String findStorageKey(String owner,long id)throws SQLException{String col=switch(owner){case"POST"->"post_id";case"COMMENT"->"comment_id";case"MESSAGE"->"message_id";default->throw new IllegalArgumentException();};try(Connection c=DBConnection.getConnection();PreparedStatement s=c.prepareStatement("SELECT storage_key FROM attachments WHERE "+col+"=?")){s.setLong(1,id);try(ResultSet r=s.executeQuery()){return r.next()?r.getString(1):null;}}}
 private Attachment map(ResultSet r)throws SQLException{return new Attachment(r.getLong("attachment_id"),nullable(r,"post_id"),nullable(r,"comment_id"),nullable(r,"message_id"),r.getString("original_filename"),r.getString("storage_key"),r.getString("mime_type"),r.getLong("file_size"));}private Long nullable(ResultSet r,String c)throws SQLException{long v=r.getLong(c);return r.wasNull()?null:v;}
}
