package com.studenthub.service;
import static org.junit.jupiter.api.Assertions.*;
import java.lang.reflect.*;import java.sql.*;import java.util.*;import org.junit.jupiter.api.Test;
class AccountDeletionServiceTest {
 @Test void wrongPasswordRollsBackWithoutMutation()throws Exception{Fixture f=new Fixture("STUDENT",2,1);var r=f.service(false).deleteOwnAccount(41,"wrong");assertEquals("ACCOUNT_DELETE_PASSWORD_INVALID",r.code());assertTrue(f.rolledBack);assertFalse(f.committed);assertTrue(f.updates.isEmpty());}
 @Test void lastAdminIsProtected()throws Exception{Fixture f=new Fixture("ADMIN",1,1);var r=f.service(true).deleteOwnAccount(41,"correct");assertEquals("ACCOUNT_DELETE_LAST_ADMIN",r.code());assertTrue(f.rolledBack);assertFalse(f.committed);}
 @Test void studentDeletionAnonymizesAndPreservesSharedRows()throws Exception{Fixture f=new Fixture("STUDENT",2,1);var r=f.service(true).deleteOwnAccount(41,"correct");assertTrue(r.success());assertEquals("photo.jpg",r.profileImage());assertTrue(f.committed);assertTrue(f.updates.stream().anyMatch(s->s.startsWith("UPDATE users SET")));assertTrue(f.updates.stream().anyMatch(s->s.startsWith("DELETE FROM reactions")));assertFalse(f.updates.stream().anyMatch(s->s.matches("(?i).*DELETE FROM (users|posts|comments|messages|private_messages|private_conversations|universities).*")));assertFalse(f.updates.stream().anyMatch(s->s.contains("universities")));}
 @Test void sharedUniversityRecordsAreNeverMutated()throws Exception{Fixture f=new Fixture("STUDENT",2,1);assertTrue(f.service(true).deleteOwnAccount(41,"correct").success());assertTrue(f.updates.stream().noneMatch(s->s.toLowerCase(Locale.ROOT).contains("universities")));}
 @Test void deletingUserAScopesEveryMutationToUserA()throws Exception{Fixture f=new Fixture("STUDENT",2,1);assertTrue(f.service(true).deleteOwnAccount(41,"correct").success());assertFalse(f.boundUserIds.isEmpty());assertTrue(f.boundUserIds.stream().allMatch(id->id==41L));}
 @Test void successfulDeletionReplacesAuthenticationCredentials()throws Exception{Fixture f=new Fixture("STUDENT",2,1);assertTrue(f.service(true).deleteOwnAccount(41,"correct").success());assertTrue(f.updates.stream().anyMatch(s->s.contains("username=NULL,student_id=NULL")));assertTrue(f.boundStrings.stream().anyMatch(s->s.matches("deleted-[a-f0-9]{32}@invalid\\.studenthub")));assertTrue(f.boundStrings.stream().noneMatch("hash"::equals));}
 @Test void crCanDeleteOwnAccount()throws Exception{Fixture f=new Fixture("CR",2,1);assertTrue(f.service(true).deleteOwnAccount(72,"correct").success());assertTrue(f.committed);}
 @Test void databaseFailureRollsBackEntireTransaction()throws Exception{Fixture f=new Fixture("STUDENT",2,0);assertThrows(SQLException.class,()->f.service(true).deleteOwnAccount(41,"correct"));assertTrue(f.rolledBack);assertFalse(f.committed);}
 @Test void absentOptionalFeatureTablesDoNotBlockDeletion()throws Exception{Fixture f=new Fixture("STUDENT",2,1);f.optionalTablesPresent=false;assertTrue(f.service(true).deleteOwnAccount(41,"correct").success());assertTrue(f.committed);}
 private static final class Fixture{final String role;final int admins,accountRows;final List<String> updates=new ArrayList<>(),boundStrings=new ArrayList<>();final List<Long> boundUserIds=new ArrayList<>();boolean committed,rolledBack,optionalTablesPresent=true;Fixture(String r,int a,int n){role=r;admins=a;accountRows=n;}AccountDeletionService service(boolean ok){return new AccountDeletionService(this::connection,(p,h)->ok);}Connection connection(){return proxy(Connection.class,(p,m,a)->switch(m.getName()){case"getAutoCommit"->true;case"setAutoCommit","close"->null;case"commit"->{committed=true;yield null;}case"rollback"->{rolledBack=true;yield null;}case"prepareStatement"->statement((String)a[0]);default->defaults(m.getReturnType());});}PreparedStatement statement(String sql){return proxy(PreparedStatement.class,(p,m,a)->{if(m.getName().equals("setLong")){boundUserIds.add((Long)a[1]);return null;}if(m.getName().equals("setString")){if(!sql.startsWith("SELECT 1 FROM information_schema"))boundStrings.add((String)a[1]);return null;}if(m.getName().equals("close"))return null;if(m.getName().equals("executeQuery")){if(sql.startsWith("SELECT password_hash"))return result(Collections.singletonList(new Object[]{"hash",role,"photo.jpg"}));if(sql.startsWith("SELECT 1 FROM information_schema"))return result(optionalTablesPresent?Collections.singletonList(new Object[]{1}):Collections.emptyList());List<Object[]> rows=new ArrayList<>();for(int i=0;i<admins;i++)rows.add(new Object[]{(long)i+1});return result(rows);}if(m.getName().equals("executeUpdate")){updates.add(sql);return sql.startsWith("UPDATE users SET")?accountRows:1;}return defaults(m.getReturnType());});}ResultSet result(List<Object[]> rows){int[] i={-1};return proxy(ResultSet.class,(p,m,a)->switch(m.getName()){case"next"->++i[0]<rows.size();case"getString"->String.valueOf(rows.get(i[0])[(Integer)a[0]-1]);case"getLong"->((Number)rows.get(i[0])[(Integer)a[0]-1]).longValue();case"close"->null;default->defaults(m.getReturnType());});}}
 @SuppressWarnings("unchecked")static<T>T proxy(Class<T>type,InvocationHandler h){return(T)Proxy.newProxyInstance(type.getClassLoader(),new Class[]{type},h);}static Object defaults(Class<?>t){if(!t.isPrimitive())return null;if(t==boolean.class)return false;if(t==long.class)return 0L;return 0;}
}
