<%@ page contentType="text/html;charset=UTF-8" language="java" %>
<%@ taglib prefix="c" uri="jakarta.tags.core" %>
<!doctype html><html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>Sign in | StudentHub</title><link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"><script src="${pageContext.request.contextPath}/assets/js/theme.js"></script><script src="${pageContext.request.contextPath}/assets/js/main.js?v=20260822-2" defer></script><link href="${pageContext.request.contextPath}/assets/css/main.css?v=20260822-2" rel="stylesheet"><link href="${pageContext.request.contextPath}/assets/css/auth-refined.css?v=20260822" rel="stylesheet"></head>
<body class="auth-page auth-page-refined"><jsp:include page="auth-nav.jsp"><jsp:param name="accountPath" value="/register"/><jsp:param name="accountLabel" value="Register"/></jsp:include><main class="auth-main"><div class="auth-card card border-0"><div class="card-body p-4 p-md-5">
<div class="auth-card-brand"><span class="auth-brand-mark"><span>S</span></span></div><p class="auth-eyebrow">Welcome back</p><h1 class="h2">Sign in to StudentHub</h1><p class="text-secondary">Continue to your academic community.</p>
<c:if test="${not empty message}"><div class="alert alert-success"><c:out value="${message}"/></div></c:if><c:if test="${not empty error}"><div class="alert alert-danger"><c:out value="${error}"/></div></c:if>
<form method="post" action="${pageContext.request.contextPath}/login"><input type="hidden" name="csrfToken" value="<c:out value='${csrfToken}'/>">
<div class="mb-3"><label class="form-label" for="login">Student ID or email</label><input class="form-control" id="login" name="login" maxlength="120" autocomplete="username" required></div>
<div class="mb-2"><label class="form-label" for="loginPassword">Password</label><div class="password-field"><input class="form-control" type="password" id="loginPassword" name="password" maxlength="128" autocomplete="current-password" required><button type="button" class="password-toggle" data-input="loginPassword" aria-label="Show password"><svg viewBox="0 0 24 24" aria-hidden="true"><path d="M2 12s3-7 10-7 10 7 10 7-3 7-10 7-10-7-10-7Z"/><circle cx="12" cy="12" r="3"/></svg></button></div></div>
<div class="text-end mb-4"><a href="${pageContext.request.contextPath}/forgot-password">Forgot password?</a></div><button class="btn btn-primary w-100" type="submit">Sign In</button></form><p class="mt-4 mb-0 text-center">New to StudentHub? <a href="${pageContext.request.contextPath}/register">Create an account</a></p>
</div></div></main></body></html>
