<%@ page contentType="text/html;charset=UTF-8" language="java" %>
<%@ taglib prefix="c" uri="jakarta.tags.core" %>
<!doctype html><html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>Register | StudentHub</title><link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"><script src="${pageContext.request.contextPath}/assets/js/theme.js?v=${applicationScope.assetVersion}"></script><script src="${pageContext.request.contextPath}/assets/js/main.js?v=${applicationScope.assetVersion}" defer></script><link href="${pageContext.request.contextPath}/assets/css/main.css?v=${applicationScope.assetVersion}" rel="stylesheet"><link href="${pageContext.request.contextPath}/assets/css/auth-refined.css?v=${applicationScope.assetVersion}" rel="stylesheet"></head>
<body class="auth-page auth-page-refined"><jsp:include page="auth-nav.jsp"><jsp:param name="accountPath" value="/login"/><jsp:param name="accountLabel" value="Log In"/></jsp:include><main class="auth-main"><div class="auth-card auth-card-wide card border-0"><div class="card-body p-4 p-md-5">
<div class="auth-card-brand"><span class="auth-brand-mark"><span>S</span></span></div><p class="auth-eyebrow">Join StudentHub</p><h1 class="h2">Create your student account</h1><p class="text-secondary">Set up your academic identity and stay connected.</p>
<c:if test="${not empty error}"><div class="alert alert-danger"><c:out value="${error}"/></div></c:if>
<form method="post" action="${pageContext.request.contextPath}/register" novalidate><input type="hidden" name="csrfToken" value="<c:out value='${csrfToken}'/>">
<div class="auth-form-grid"><div><label class="form-label" for="studentId">Student ID</label><input class="form-control" id="studentId" name="studentId" maxlength="8" pattern="TNT-[0-9]{4}" placeholder="TNT-0001" required></div><div><label class="form-label" for="fullName">Full name</label><input class="form-control" id="fullName" name="fullName" maxlength="100" autocomplete="name" required></div></div>
<div class="mt-3"><label class="form-label" for="email">Email</label><input class="form-control" type="email" id="email" name="email" maxlength="120" autocomplete="email" required></div>
<div class="auth-form-grid mt-3"><div><label class="form-label" for="registerPassword">Password</label><div class="password-field"><input class="form-control" type="password" id="registerPassword" name="password" minlength="8" maxlength="128" autocomplete="new-password" required><button type="button" class="password-toggle" data-input="registerPassword" aria-label="Show password"><svg viewBox="0 0 24 24" aria-hidden="true"><path d="M2 12s3-7 10-7 10 7 10 7-3 7-10 7-10-7-10-7Z"/><circle cx="12" cy="12" r="3"/></svg></button></div></div><div><label class="form-label" for="confirmPassword">Confirm password</label><div class="password-field"><input class="form-control" type="password" id="confirmPassword" name="confirmPassword" maxlength="128" autocomplete="new-password" required><button type="button" class="password-toggle" data-input="confirmPassword" aria-label="Show password"><svg viewBox="0 0 24 24" aria-hidden="true"><path d="M2 12s3-7 10-7 10 7 10 7-3 7-10 7-10-7-10-7Z"/><circle cx="12" cy="12" r="3"/></svg></button></div></div></div><div class="form-text mt-2">At least 8 characters with uppercase, lowercase, and a number.</div>
<button class="btn btn-primary w-100 mt-4" type="submit">Create account</button></form><p class="mt-4 mb-0 text-center">Already registered? <a href="${pageContext.request.contextPath}/login">Sign in</a></p>
</div></div></main></body></html>
