package com.studenthub.util;
import java.io.*;import java.nio.file.*;import java.util.*;import java.util.regex.Pattern;
public class AttachmentStorage implements ContentStorage {
    private static final Pattern KEY=Pattern.compile("^[a-f0-9-]{36}\\.[a-z0-9]{2,5}$"); private final Path directory;
    public AttachmentStorage(){this(resolve());} AttachmentStorage(Path path){directory=path==null?null:path.toAbsolutePath().normalize();}
    public AttachmentUpload save(AttachmentValidator.Validated value)throws IOException{if(directory==null)throw new IOException("Persistent attachment storage is not configured");Files.createDirectories(directory);String key=UUID.randomUUID()+"."+value.extension();Path p=safe(key).orElseThrow();Files.write(p,value.content(),StandardOpenOption.CREATE_NEW);return new AttachmentUpload(value.originalFilename(),key,value.mimeType(),value.content().length);}
    public AttachmentUpload saveStream(String filename,String mime,long declaredSize,InputStream input)throws IOException{
        if(directory==null)throw new IOException("STORAGE_UNAVAILABLE");if(declaredSize<=0||declaredSize>UploadPolicy.limit(mime))throw new IOException("FILE_TOO_LARGE");Files.createDirectories(directory);if(!Files.isWritable(directory))throw new IOException("STORAGE_UNAVAILABLE");
        String temporary=UUID.randomUUID()+".part",key=null;Path temp=directory.resolve(temporary).normalize();if(!temp.getParent().equals(directory))throw new IOException("INVALID_PATH");long written=0;byte[] header=new byte[32],buffer=new byte[64*1024];int headerLength=0;
        try(OutputStream out=Files.newOutputStream(temp,StandardOpenOption.CREATE_NEW)){int count;while((count=input.read(buffer))!=-1){written+=count;if(written>UploadPolicy.limit(mime))throw new IOException("FILE_TOO_LARGE");if(headerLength<header.length){int copy=Math.min(count,header.length-headerLength);System.arraycopy(buffer,0,header,headerLength,copy);headerLength+=copy;}out.write(buffer,0,count);}}
        catch(Exception e){Files.deleteIfExists(temp);throw e;}
        AttachmentValidator.Result checked=AttachmentValidator.validateHeader(filename,mime,Arrays.copyOf(header,headerLength),written);if(!checked.valid()){Files.deleteIfExists(temp);throw new IOException("INVALID_UPLOAD:"+checked.error());}
        key=UUID.randomUUID()+"."+checked.value().extension();Path destination=safe(key).orElseThrow();try{try{Files.move(temp,destination,StandardCopyOption.ATOMIC_MOVE);}catch(AtomicMoveNotSupportedException e){Files.move(temp,destination);}return new AttachmentUpload(checked.value().originalFilename(),key,checked.value().mimeType(),written);}catch(Exception e){Files.deleteIfExists(temp);if(key!=null)Files.deleteIfExists(destination);throw e;}
    }
    public Optional<Path> find(String key){return safe(key).filter(Files::isRegularFile);} public void delete(String key){safe(key).ifPresent(p->{try{Files.deleteIfExists(p);}catch(IOException ignored){}});}
    private Optional<Path> safe(String key){if(directory==null||key==null||!KEY.matcher(key).matches())return Optional.empty();Path p=directory.resolve(key).normalize();return p.getParent()!=null&&p.getParent().equals(directory)?Optional.of(p):Optional.empty();}
    public boolean isConfigured(){return directory!=null;} public boolean ensureWritable(){if(directory==null)return false;try{Files.createDirectories(directory);return Files.isDirectory(directory)&&Files.isWritable(directory);}catch(IOException|SecurityException e){return false;}}
    private static Path resolve(){String configured=System.getenv("STUDENTHUB_ATTACHMENT_DIR");if(configured!=null&&!configured.isBlank())return Path.of(configured);String root=System.getenv("STUDENTHUB_UPLOAD_DIR");if(root!=null&&!root.isBlank())return Path.of(root).resolve("attachments");if("production".equalsIgnoreCase(System.getenv("APP_ENV")))return null;return Path.of(System.getProperty("java.io.tmpdir"),"studenthub-uploads","attachments");}
}
