package com.studenthub.controller;
import static org.junit.jupiter.api.Assertions.*;
import com.studenthub.service.AccountDeletionService;import com.studenthub.util.*;import jakarta.servlet.http.*;import java.io.*;import java.lang.reflect.Proxy;import java.sql.SQLException;import java.util.*;import java.util.concurrent.atomic.*;import org.junit.jupiter.api.Test;
class DeleteAccountServletTest {
 @Test void unauthenticatedIsRejected()throws Exception{Exchange x=exchange(null,"token","token","password");servlet(serviceReturning(result(true,"ACCOUNT_DELETE_OK"))).doPost(x.request,x.response);assertResponse(x,401,"ACCOUNT_DELETE_UNAUTHENTICATED");}
 @Test void invalidCsrfIsRejectedBeforeService()throws Exception{AtomicInteger calls=new AtomicInteger();Exchange x=exchange(7L,"token","wrong","password");servlet(new AccountDeletionService(){@Override public Result deleteOwnAccount(long id,String password){calls.incrementAndGet();return result(true,"ACCOUNT_DELETE_OK");}}).doPost(x.request,x.response);assertResponse(x,403,"ACCOUNT_DELETE_CSRF_INVALID");assertEquals(0,calls.get());}
 @Test void wrongPasswordReturnsStructuredCodeAndKeepsSession()throws Exception{Exchange x=exchange(7L,"token","token","wrong");servlet(serviceReturning(result(false,"ACCOUNT_DELETE_PASSWORD_INVALID"))).doPost(x.request,x.response);assertResponse(x,400,"ACCOUNT_DELETE_PASSWORD_INVALID");assertFalse(x.invalidated.get());}
 @Test void successUsesSessionUserPasswordAndInvalidatesSession()throws Exception{AtomicLong id=new AtomicLong();AtomicReference<String> password=new AtomicReference<>();AccountDeletionService service=new AccountDeletionService(){@Override public Result deleteOwnAccount(long userId,String currentPassword){id.set(userId);password.set(currentPassword);return result(true,"ACCOUNT_DELETE_OK");}};Exchange x=exchange(91L,"token","token","correct");servlet(service).doPost(x.request,x.response);assertResponse(x,200,"ACCOUNT_DELETE_OK");assertEquals(91,id.get());assertEquals("correct",password.get());assertTrue(x.invalidated.get());}
 @Test void databaseFailureIsSanitized()throws Exception{AccountDeletionService service=new AccountDeletionService(){@Override public Result deleteOwnAccount(long id,String password)throws SQLException{throw new SQLException("secret SQL","23000",1451);}};Exchange x=exchange(7L,"token","token","correct");servlet(service).doPost(x.request,x.response);assertResponse(x,500,"ACCOUNT_DELETE_DB_ERROR");assertFalse(x.body.toString().contains("secret"));}
 private DeleteAccountServlet servlet(AccountDeletionService service){return new DeleteAccountServlet(service,new ProfilePhotoStorage());}private AccountDeletionService serviceReturning(AccountDeletionService.Result r){return new AccountDeletionService(){@Override public Result deleteOwnAccount(long id,String password){return r;}};}private AccountDeletionService.Result result(boolean ok,String code){return new AccountDeletionService.Result(ok,code,null);}
 private Exchange exchange(Long id,String sessionToken,String suppliedToken,String password){Map<String,Object> values=new HashMap<>();if(id!=null)values.put("userId",id);values.put(CsrfToken.SESSION_KEY,sessionToken);AtomicBoolean invalidated=new AtomicBoolean();HttpSession session=proxy(HttpSession.class,(p,m,a)->{if(m.getName().equals("getAttribute"))return values.get(a[0]);if(m.getName().equals("invalidate")){invalidated.set(true);return null;}return null;});HttpServletRequest request=proxy(HttpServletRequest.class,(p,m,a)->switch(m.getName()){case"getSession"->session;case"getParameter"->"csrfToken".equals(a[0])?suppliedToken:password;case"getContextPath"->"";default->null;});AtomicInteger status=new AtomicInteger(200);StringWriter body=new StringWriter();PrintWriter writer=new PrintWriter(body);HttpServletResponse response=proxy(HttpServletResponse.class,(p,m,a)->{if(m.getName().equals("setStatus"))status.set((Integer)a[0]);if(m.getName().equals("getWriter"))return writer;return null;});return new Exchange(request,response,status,body,invalidated);}
 private void assertResponse(Exchange x,int status,String code){assertEquals(status,x.status.get());assertTrue(x.body.toString().contains(code));} @SuppressWarnings("unchecked")private<T>T proxy(Class<T>type,java.lang.reflect.InvocationHandler h){return(T)Proxy.newProxyInstance(type.getClassLoader(),new Class[]{type},h);}private record Exchange(HttpServletRequest request,HttpServletResponse response,AtomicInteger status,StringWriter body,AtomicBoolean invalidated){}
}
