<%@ page contentType="text/html;charset=UTF-8" language="java" %><%@ taglib prefix="c" uri="jakarta.tags.core" %>
<!doctype html><html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Create announcement | StudentHub</title><link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"><script src="${pageContext.request.contextPath}/assets/js/main.js?v=${applicationScope.assetVersion}" defer></script><script src="${pageContext.request.contextPath}/assets/js/announcement-form.js?v=${applicationScope.assetVersion}" defer></script><link href="${pageContext.request.contextPath}/assets/css/main.css?v=${applicationScope.assetVersion}" rel="stylesheet"></head>
<body class="auth-page create-announcement-page"><main class="container"><div class="auth-card create-post-card card border-0 shadow-lg mx-auto"><div class="card-body"><a href="${pageContext.request.contextPath}/home" class="create-post-back text-decoration-none">← Back to home</a><header class="create-post-heading"><p class="eyebrow mb-2">Share an update</p><h1>Create an announcement</h1><p>Publish clear, timely information for students in the selected scope.</p></header><c:if test="${not empty error}"><div class="alert alert-danger" role="alert"><c:out value="${error}" /></div></c:if>
<form class="create-post-form" method="post" enctype="multipart/form-data" action="${pageContext.request.contextPath}/posts/create" data-create-post-form><input type="hidden" name="csrfToken" value="<c:out value='${csrfToken}' />">
<div><label class="form-label" for="categoryId">Category</label><select class="form-select" id="categoryId" name="categoryId" required><option value="">Select category</option><c:forEach var="category" items="${categories}"><option value="${category.categoryId}" data-name="<c:out value='${category.categoryName}' />"><c:out value="${category.categoryName}" /></option></c:forEach></select></div>
<div id="deadlineContainer" hidden><label class="form-label" for="deadlineDate">Deadline <span class="text-danger" aria-hidden="true">*</span> <span class="field-help">Required for Assignment, Tutorial, and Exam</span></label><input type="datetime-local" class="form-control" id="deadlineDate" name="deadlineDate"></div>
<div><label class="form-label" for="visibility">Visibility</label><select class="form-select" id="visibility" name="visibility" required><option value="ALL">All students</option><option value="SEMESTER">My semester</option><option value="SECTION">My section</option></select></div>
<div><label class="form-label" for="title">Title</label><input class="form-control" id="title" name="title" maxlength="200" required></div>
<div><label class="form-label" for="content">Content</label><textarea class="form-control create-post-content" id="content" name="content" rows="7" maxlength="10000"></textarea></div>
<div class="announcement-upload"><span class="form-label">Attachment <span class="optional-label">Optional</span></span><div class="announcement-upload-card" data-upload-card><span class="announcement-upload-icon" aria-hidden="true">↥</span><div class="announcement-upload-copy"><strong data-upload-filename>No file selected</strong><small>Image (10 MB), video (50 MB), audio, PDF, or document (20 MB). One file only.</small></div><label class="btn btn-outline-primary announcement-file-button" for="postAttachment">Choose file</label><input class="visually-hidden" id="postAttachment" type="file" name="attachment" accept="image/jpeg,image/png,image/webp,video/mp4,video/webm,audio/mpeg,audio/mp4,audio/aac,audio/wav,audio/ogg,audio/webm,.pdf,.doc,.docx,.ppt,.pptx,.xls,.xlsx,.txt,.zip" data-upload-input><button class="announcement-file-remove" type="button" data-upload-remove hidden>Remove</button></div><p class="announcement-upload-error" data-upload-error role="alert" aria-live="polite"></p></div>
<button class="btn btn-primary publish-announcement-button" type="submit" data-publish-button>Publish announcement</button></form>
</div></div></main></body></html>
