<%@ page contentType="text/html;charset=UTF-8" language="java" %><%@ taglib prefix="c" uri="jakarta.tags.core" %>
<section class="post-feed" aria-label="StudentHub announcements"><c:choose><c:when test="${empty posts}"><div class="empty-state"><div class="empty-icon">SH</div><h3>No announcements yet.</h3><p>New announcements will appear here.</p></div></c:when><c:otherwise><c:forEach var="post" items="${posts}"><article class="post-card"><header class="post-header"><div class="avatar"><c:out value="${post.authorName.substring(0, 1)}" /></div><div class="post-author"><div><strong><c:out value="${post.authorName}" /></strong><span class="role-badge role-${post.authorRole}"><c:out value="${post.authorRole}" /></span></div><time><c:out value="${post.createdLabel}" /></time></div><c:if test="${not empty post.categoryName}"><span class="post-category"><c:out value="${post.categoryName}" /></span></c:if></header><div class="visibility-label"><c:out value="${post.visibility}" /></div><div class="post-content"><h3><c:out value="${post.title}" /></h3><p><c:out value="${post.content}" /></p></div>
<c:if test="${not empty post.attachments}">
<div class="post-attachments mb-3">
<c:forEach var="att" items="${post.attachments}">
<div class="attachment-item mb-2">
<c:choose>
<c:when test="${att.image}">
<div class="attachment-image-wrap my-2"><a href="${pageContext.request.contextPath}/attachments/view?id=${att.attachmentId}" target="_blank"><img src="${pageContext.request.contextPath}/attachments/view?id=${att.attachmentId}" alt="<c:out value='${att.originalFilename}' />" class="img-fluid rounded border" style="max-height:300px;object-fit:contain;"></a></div>
</c:when>
<c:when test="${att.video}">
<div class="attachment-video-wrap my-2"><video controls class="w-100 rounded border" style="max-height:320px;"><source src="${pageContext.request.contextPath}/attachments/view?id=${att.attachmentId}" type="${att.mimeType}">Your browser does not support the video tag.</video></div>
</c:when>
<c:otherwise>
<div class="attachment-file-box p-2 rounded border bg-body-tertiary d-flex align-items-center justify-content-between"><div class="d-flex align-items-center gap-2"><span style="font-size:1.2rem;">📎</span><div><div class="fw-semibold text-truncate" style="max-width:240px;"><c:out value="${att.originalFilename}" /></div><small class="text-secondary"><c:out value="${att.formattedSize}" /></small></div></div><div class="d-flex gap-2"><a href="${pageContext.request.contextPath}/attachments/view?id=${att.attachmentId}" target="_blank" class="btn btn-sm btn-outline-secondary">View</a><a href="${pageContext.request.contextPath}/attachments/download?id=${att.attachmentId}" class="btn btn-sm btn-primary">Download</a></div></div>
</c:otherwise>
</c:choose>
</div>
</c:forEach>
</div>
</c:if><footer class="post-footer"><div class="engagement-controls"><form method="post" action="${pageContext.request.contextPath}/posts/react"><input type="hidden" name="csrfToken" value="<c:out value='${csrfToken}' />"><input type="hidden" name="postId" value="${post.postId}"><input type="hidden" name="source" value="${pageContext.request.servletPath eq '/home' ? 'home' : 'announcements'}"><input type="hidden" name="category" value="<c:out value='${selectedCategory}' />"><button class="reaction-button ${post.reactedByCurrentUser ? 'active' : ''}" type="submit" aria-pressed="${post.reactedByCurrentUser}" aria-label="${post.reactedByCurrentUser ? 'Remove like' : 'Like announcement'}">${post.reactedByCurrentUser ? '♥' : '♡'} <strong><c:out value="${post.reactionCount}" /></strong></button></form><a class="comments-link" href="${pageContext.request.contextPath}/posts/comments?postId=${post.postId}">Comments <strong><c:out value="${post.commentCount}" /></strong></a></div><c:if test="${sessionScope.role eq 'ADMIN' or (sessionScope.role eq 'CR' and sessionScope.userId eq post.authorId)}"><div class="post-management"><a href="${pageContext.request.contextPath}/posts/edit?id=${post.postId}">Edit</a><form method="post" action="${pageContext.request.contextPath}/posts/delete" onsubmit="return confirm('Are you sure you want to delete this announcement?');"><input type="hidden" name="csrfToken" value="<c:out value='${csrfToken}' />"><input type="hidden" name="id" value="${post.postId}"><button type="submit">Delete</button></form></div></c:if></footer></article></c:forEach></c:otherwise></c:choose></section>
